### PR TITLE
Fix #33 - two failing tests and some updates

### LINKED ISSUE #33: Two tests are currently failing (spring-framework: getConverter, mockito: answer)
spring-framework-GenericConversionService-getConverter:

image

Z_mockito-ReturnsArgumentAt-answer:

image

### PR DESCRIPTION
**Pull request by ataraxie**
There were two tests currently failing. This change makes them pass again. See comments on code.

### CODE REVIEW

File: clone-repositories.sh [hunk 1]
```diff
@@ -0,0 +1,28 @@
+#!/bin/bash
```
Comment (ataraxie) [inline clone-repositories.sh:1]: Just a simple shell script to clone all the required repos for running the test suite.

File: pom.xml [hunk 2]
```diff
@@ -11,7 +11,7 @@
```
Comment (ataraxie) [inline pom.xml:11]: This was a security vulnerability according to Github.

File: src/main/java/com/felixgrund/codeshovel/parser/AbstractFunction.java [hunk 3]
```diff
@@ -56,14 +56,14 @@ public AbstractFunction(E rawMethod, Commit commit, String sourceFilePath, Strin
 		// NOTE: the order of these calls does matter!
 		this.name = getInitialName(rawMethod);
 		this.parameters = getInitialParameters(rawMethod);
+		this.parentName = getInitialParentName(rawMethod);
```
Comment (ataraxie) [inline src/main/java/com/felixgrund/codeshovel/parser/AbstractFunction.java:59]: We need to do this first to be able to include it in the function ID.

File: src/main/java/com/felixgrund/codeshovel/parser/AbstractFunction.java [hunk 4]
```diff
@@ -77,7 +77,7 @@ private String getIdParameterString() {
 	}
 
 	protected String getInitialId(E rawMethod) {
-		String ident = getName();
+		String ident = getParentName() + "#" + getName();
```
Comment (ataraxie) [inline src/main/java/com/felixgrund/codeshovel/parser/AbstractFunction.java:80]: The problem here was that a nested method had the same function ID as another method with the same name and parameters. In the end, there was only one function mapped to the ID and hence the wrong function was taken as "matched function". By adding the parent name to the function ID, nested functions will differ from top-level functions.

File: src/test/java/com/felixgrund/codeshovel/MainDynamicStubTest.java [hunk 5]
```diff
@@ -66,10 +66,11 @@
 			String json = FileUtils.readFileToString(file, "utf-8");
 			StartEnvironment startEnv = GSON.fromJson(json, StartEnvironment.class);
 			startEnv.setEnvName(envName);
-			boolean stubWhitelisted = envName.startsWith(RUN_ONLY_TEST);
-			boolean isBlacklist = RUN_ONLY_TEST.startsWith("!");
+			boolean hasAnyIncludesOrIncludes = RUN_ONLY_TEST != null;
```
Comment (ataraxie) [inline src/test/java/com/felixgrund/codeshovel/MainDynamicStubTest.java:69]: This was quite messy... should now be a bit better.

File: src/test/resources/stubs/java/Z_mockito-ReturnsArgumentAt-answer.json [hunk 6]
```diff
@@ -12,6 +12,7 @@
     "5a2415278e865ac0becfcbaf8626d4f0c3b17a70": "Yfilerename",
     "4b81c5d36e1ab63412c9a55d982cf5c6df238dab": "Ymultichange(Yfilerename,Ybodychange)",
     "dda1c41ea0fe96abfe62bb1bfd1e1d51d2c5c509": "Ybodychange",
-    "5490d9b2fc7814bc4c1efe5a66f05ce5874d38bc": "Ymultichange(Ymovefromfile,Yreturntypechange,Ybodychange)"
+    "5490d9b2fc7814bc4c1efe5a66f05ce5874d38bc": "Ymultichange(Ymovefromfile,Yreturntypechange,Ybodychange)",
+    "ae7ad39c99ea7ffecd84c1453aa26f44846f066a": "Yintroduced"
```
Comment (ataraxie) [inline src/test/resources/stubs/java/Z_mockito-ReturnsArgumentAt-answer.json:16]: This was really just missing the introduction commit. I checked it and it's all correct.

**Review by ataraxie — COMMENTED** [review]
Left a few comments on the diff.
